name: Lint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install requirements
        run: python3 -m pip install -r requirements.txt

      - name: Lint
        run: python3 -m ruff check .

      - name: Format
        run: python3 -m ruff format . --check

  markdownlint:
    name: "Markdown Lint"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@61389a0a35cfb8cf0b80e55b01c4e6a9e11b4c43 # v4.0.4
        with:
          node-version: "lts/*"

      - name: Install markdownlint-cli2
        run: npm install

      - name: Lint Markdown files
        run: npm run lint:markdown
